# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: ./distro/stratis-cli.spec

# add or remove files that should be synced
files_to_sync:
    - stratis-cli.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: stratis-cli
# downstream (Fedora) RPM package name
downstream_package_name: stratis-cli

actions:
  create-archive:
    - "sh -c 'python3 ./distro/create_artifacts.py ./distro/ stratis-cli $(python3 setup.py --version)'"
    - "sh -c 'echo distro/stratis-cli-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"

srpm_build_deps:
  - python3-pip # "python3 setup.py --version" needs it

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-stable
